global:
  resolve_timeout: 5m

  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'kakarlapudikoushilvarma@gmail.com'
  smtp_auth_username: 'kakarlapudikoushilvarma@gmail.com'
  smtp_auth_password: 'ihop hmay gjqf niro'

route:
  receiver: email-alert

receivers:
  - name: email-alert

    email_configs:
      - to: 'kakarlapudikoushilvarma@gmail.com'
        send_resolved: true